#!/usr/bin/env bash

VERSION="dotfiles v0.1"

BASE_DIR="$HOME/.vim"
PATHOGEN_DIR="$BASE_DIR/autoload"
BUNDLES_DIR="$BASE_DIR/bundle"

DOTS_DIR="$HOME/Development/dotfiles"
FILES=".aliases .bashrc .zshrc .vimrc"

help_message() {
  echo "Usage: dotfiles [OPTION]..."
  echo "Mandatory arguments to long options are mandatory for short options too."
  echo "-h, --help"
  echo "    display this help and exit"
  echo "-r, --restore"
  echo "    restore the saved files to the home directory"
  echo "-u, --update"
  echo "    save the modified files in the repository directory"
  echo "-p, --plugins"
  echo "    search for updates(git) in the vim plugins directory"
  echo "-c, --colorscheme"
  echo "    download my favorite themes"
}

bkp() {
  if [[ $1 -nt $2 ]]; then
    cp $1 $2
    echo -e "\e[1m$3:\e[0m \e[33mModified\e[0m"
  fi
}

restore() {
  for dotfile in $FILES; do
    echo -e "\e[1m$dotfile: \e[0m \e[32mRestored\e[0m"
    cp $DOTS_DIR/$dotfile $HOME/
  done
}

update() {
  for dotfile in $FILES; do
    bkp $HOME/$dotfile $DOTS_DIR/$dotfile $dotfile
  done
}

colorscheme() {
  # download jellybeans theme
  if [[ ! -f "$BASE_DIR/colors/jellybeans.vim" ]]; then
    echo "Downloading jellybeans.vim..."
    wget -cq https://raw.githubusercontent.com/nanotech/jellybeans.vim/master/colors/jellybeans.vim -O $HOME/.vim/colors/jellybeans.vim
  fi
}

vimplugins() {
  if [[ -d "$PATHOGEN_DIR" ]]; then
    echo "Updating pathogen in $PATHOGEN_DIR..."
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  fi
  if [[ -d "$BUNDLES_DIR" ]]; then
    echo "Updating bundles in $BUNDLES_DIR..."
    for bundle in "$BUNDLES_DIR/"*; do
      if [[ -d "$bundle/.git" ]]; then
        echo -ne "Bundle: \e[34m$bundle\e[0m ..... "
        cd "$bundle"
        git pull
      fi
    done
  fi
}

case "$1" in
  -v | --version)
    echo $VERSION
    exit 0
    ;;

  -h | --help)
    help_message
    exit 0
    ;;

  -r | --restore)
    restore
    ;;

  -u | --update)
    update
    ;;

  -p | --plugins)
    vimplugins
    ;;

  -c | --colorscheme)
    colorscheme
    ;;

  *)
    help_message
    exit 1
    ;;
esac
